// ============================================================
// Nova Webs — Portfolio Seed Data
// Real working URLs with premium Unsplash preview images
// ============================================================

import { savePortfolioProjects, generateId, type PortfolioProject } from "./data-store";

const DEMO_PROJECTS: PortfolioProject[] = [
  {
    id: generateId(),
    title: "The Flavor Restaurant",
    category: "Restaurant",
    description: "Modern restaurant-style booking experience with premium UI and seamless reservation system.",
    longDescription: "A premium dining platform inspired by industry leaders. Features include interactive menu browsing, real-time table reservations, online ordering with payment integration, and a customer loyalty program. Designed to convert visitors into diners.",
    technologies: ["Next.js", "Stripe", "Tailwind CSS", "Prisma"],
    clientName: "",
    completionDate: "2026-07-01",
    featured: true,
    order: 1,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=85",
    screenshots: [],
    liveUrl: "https://www.airbnb.com",
    githubUrl: "",
    caseStudy: "A modern dining platform designed to create an immersive experience that mirrors quality dining. Features interactive menus with dietary filters, table reservations with real-time availability, and integrated payment processing.",
    metrics: "+120% reservations",
    createdAt: "2026-07-01T00:00:00Z",
    updatedAt: "2026-07-15T00:00:00Z",
  },
  {
    id: generateId(),
    title: "Planet Fitness",
    category: "Gym & Fitness",
    description: "Professional fitness website with memberships, class scheduling, and trainer profiles.",
    longDescription: "A comprehensive fitness platform designed to convert visitors into members. Features class scheduling with real-time capacity tracking, member profiles with progress tracking, trainer portals, and integrated payment processing for memberships.",
    technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    clientName: "",
    completionDate: "2026-06-20",
    featured: true,
    order: 2,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=900&q=85",
    screenshots: [],
    liveUrl: "https://www.planetfitness.com",
    githubUrl: "",
    caseStudy: "A high-performance fitness platform featuring motivational design, easy-to-navigate class schedules with filters, and clear membership tier comparisons designed to drive signups.",
    metrics: "+85% memberships",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-20T00:00:00Z",
  },
  {
    id: generateId(),
    title: "Mayo Clinic",
    category: "Dental / Healthcare",
    description: "Modern healthcare website with appointments, patient portal, and treatment galleries.",
    longDescription: "A trust-building healthcare platform that makes patients feel welcome. Online appointment booking with real-time availability, patient portal for medical records, treatment galleries, and secure telemedicine integration.",
    technologies: ["React", "Twilio", "Tailwind CSS", "Supabase"],
    clientName: "",
    completionDate: "2026-06-10",
    featured: true,
    order: 3,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1551076805-e1869033e561?w=900&q=85",
    screenshots: [],
    liveUrl: "https://www.mayoclinic.org",
    githubUrl: "",
    caseStudy: "A healthcare platform designed to reduce patient anxiety through clean, professional design. Online booking has reduced phone call volume while improving patient satisfaction scores.",
    metrics: "+60% appointments",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-10T00:00:00Z",
  },
  {
    id: generateId(),
    title: "Stripe",
    category: "Business / SaaS",
    description: "Professional fintech platform with modern business website design and dashboard UI.",
    longDescription: "A premium B2B platform for data-driven businesses. Features include real-time analytics dashboards, team collaboration tools with role-based access, subscription billing with tiered pricing, and a public API for custom integrations.",
    technologies: ["Next.js", "TypeScript", "PostgreSQL", "Node.js"],
    clientName: "",
    completionDate: "2026-05-25",
    featured: true,
    order: 4,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1553729459-afe8f2e2d8c6?w=900&q=85",
    screenshots: [],
    liveUrl: "https://stripe.com",
    githubUrl: "",
    caseStudy: "A sophisticated business platform built for enterprise-scale operations. Real-time dashboards provide actionable insights with interactive charts and customizable reporting.",
    metrics: "3× efficiency",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-25T00:00:00Z",
  },

  {
    id: generateId(),
    title: "Framer Portfolio",
    category: "Portfolio",
    description: "Premium portfolio templates with modern UI/UX and stunning animations.",
    longDescription: "An award-winning portfolio platform that puts creative work front and center. Features include full-screen project galleries with smooth transitions, responsive layouts, customizable templates, and built-in CMS for easy content updates.",
    technologies: ["Framer", "React", "GSAP", "Motion"],
    clientName: "",
    completionDate: "2026-04-15",
    featured: true,
    order: 6,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=900&q=85",
    screenshots: [],
    liveUrl: "https://www.framer.com/templates",
    githubUrl: "",
    caseStudy: "A stunning portfolio platform designed to let creative work speak for itself. Clean layouts with subtle animations guide visitors through projects. Customizable templates make it easy to create a unique personal brand.",
    metrics: "Awwwards featured",
    createdAt: "2026-04-01T00:00:00Z",
    updatedAt: "2026-04-15T00:00:00Z",
  },
];

export function seedPortfolio() {
  savePortfolioProjects(DEMO_PROJECTS);
  console.log(`✅ Seeded ${DEMO_PROJECTS.length} portfolio projects`);
}
