// ============================================================
// Nova Webs — Seed Data
// Real working URLs and premium Unsplash images
// ============================================================

import { savePortfolioProjects, generateId, type PortfolioProject } from "./data-store";

const DEMO_PROJECTS: PortfolioProject[] = [
  {
    id: generateId(),
    title: "Restaurant Website",
    category: "Restaurant & Cafe",
    description: "A modern dining platform with immersive menu browsing, table reservation system, and real-time order management.",
    longDescription: "A complete digital ecosystem for a premium dining experience. Features include an interactive menu with dietary filters, a seamless table reservation engine with real-time availability, online ordering with payment integration, and a customer loyalty program.",
    technologies: ["Next.js", "Stripe", "Tailwind CSS", "Prisma"],
    clientName: "",
    completionDate: "2026-06-15",
    featured: true,
    order: 1,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    screenshots: [],
    liveUrl: "https://www.airbnb.com",
    githubUrl: "",
    caseStudy: "A modern dining experience platform inspired by top hospitality brands. Features include interactive menus with dietary filters, seamless table reservations with real-time availability, and online ordering with integrated payment processing.",
    metrics: "+120% online reservations",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-15T00:00:00Z",
  },
  {
    id: generateId(),
    title: "Gym & Fitness",
    category: "Health & Fitness",
    description: "High-performance fitness brand platform with class scheduling, membership management, and trainer profiles.",
    longDescription: "A dynamic fitness platform that drives membership growth. Key features include a class scheduling system with real-time capacity tracking, member profiles with progress tracking, trainer onboarding and profile management, and integrated payment processing for memberships.",
    technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    clientName: "",
    completionDate: "2026-05-20",
    featured: true,
    order: 2,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80",
    screenshots: [],
    liveUrl: "https://www.planetfitness.com",
    githubUrl: "",
    caseStudy: "A comprehensive fitness platform designed to convert visitors into members. Features motivational hero sections, easy-to-navigate class schedules with filter options, and clear membership tier comparisons with visual tables.",
    metrics: "+85% membership signups",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-20T00:00:00Z",
  },
  {
    id: generateId(),
    title: "Dental Clinic",
    category: "Healthcare & Dental",
    description: "Modern healthcare platform with patient portal, online appointment booking, treatment galleries, and telemedicine.",
    longDescription: "A trust-building healthcare website that makes patients feel welcome. Features include an online appointment booking system with real-time slot availability, a patient portal for medical records and communication, treatment galleries with before/after imagery, and secure telemedicine integration.",
    technologies: ["React", "Twilio", "Tailwind CSS", "Supabase"],
    clientName: "",
    completionDate: "2026-04-20",
    featured: true,
    order: 3,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1551076805-e1869033e561?w=800&q=80",
    screenshots: [],
    liveUrl: "https://www.mayoclinic.org",
    githubUrl: "",
    caseStudy: "A healthcare platform designed to reduce patient anxiety and build trust from the first visit. The clean, professional design uses calming colors and warm imagery. Online booking has reduced phone call volume significantly.",
    metrics: "+60% new patients",
    createdAt: "2026-04-01T00:00:00Z",
    updatedAt: "2026-04-20T00:00:00Z",
  },
  {
    id: generateId(),
    title: "Business Website",
    category: "Software & SaaS",
    description: "Premium B2B platform with analytics dashboard, team collaboration features, and enterprise-grade security.",
    longDescription: "A comprehensive business platform for data-driven teams. Features include real-time analytics dashboards with customizable widgets, team collaboration tools with role-based access, subscription billing with tiered pricing, and a public API for integrations.",
    technologies: ["Next.js", "TypeScript", "PostgreSQL", "Node.js"],
    clientName: "",
    completionDate: "2026-03-25",
    featured: true,
    order: 4,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1553729459-afe8f2e2d8c6?w=800&q=80",
    screenshots: [],
    liveUrl: "https://stripe.com",
    githubUrl: "",
    caseStudy: "A premium B2B platform built for enterprise-scale data processing. The frontend delivers optimal performance while robust APIs handle complex business logic. Real-time dashboards provide actionable insights with interactive visualizations.",
    metrics: "3× lead generation",
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-25T00:00:00Z",
  },
  {
    id: generateId(),
    title: "E-Commerce Store",
    category: "Online Retail",
    description: "Full-featured online marketplace with product catalog, secure checkout, inventory sync, and admin panel.",
    longDescription: "A complete e-commerce solution built for scale. Features include a dynamic product catalog with advanced search and filtering, secure checkout with multiple payment options, real-time inventory management with supplier sync, and a comprehensive admin dashboard for order management.",
    technologies: ["Next.js", "Stripe", "Sanity", "Redis"],
    clientName: "",
    completionDate: "2026-03-01",
    featured: true,
    order: 5,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
    screenshots: [],
    liveUrl: "https://www.shopify.com",
    githubUrl: "",
    caseStudy: "A comprehensive e-commerce platform designed to maximize conversions. Product pages feature high-resolution imagery, detailed specifications, and customer reviews. The checkout flow has been optimized to reduce cart abandonment significantly.",
    metrics: "+150% revenue",
    createdAt: "2026-02-15T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: generateId(),
    title: "Portfolio Website",
    category: "Creative Portfolio",
    description: "Minimalist designer portfolio with full-screen project galleries, custom interactions, and built-in CMS.",
    longDescription: "An award-winning portfolio website that puts the work front and center. Features include full-screen project galleries with smooth transitions, a custom cursor that responds to page elements, a built-in CMS for easy content updates, and subtle micro-interactions throughout.",
    technologies: ["Framer", "React", "GSAP", "Sanity CMS"],
    clientName: "",
    completionDate: "2026-02-10",
    featured: true,
    order: 6,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80",
    screenshots: [],
    liveUrl: "https://www.framer.com/templates",
    githubUrl: "",
    caseStudy: "A minimalist portfolio designed to let the work speak for itself. The clean layout puts project imagery front and center with subtle animations guiding visitors through the portfolio. Custom CMS integration allows independent content updates.",
    metrics: "Featured on Awwwards",
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-02-10T00:00:00Z",
  },
  {
    id: generateId(),
    title: "Real Estate Portal",
    category: "Property & Realty",
    description: "Premium property marketplace with virtual tours, AI recommendations, mortgage calculator, and agent profiles.",
    longDescription: "A cutting-edge real estate platform that transforms property discovery. Features include interactive property maps with neighborhood insights, virtual tours for immersive previews, AI-powered property recommendations based on user preferences, and a mortgage calculator with real-time rates.",
    technologies: ["Next.js", "Three.js", "Mapbox", "FastAPI"],
    clientName: "",
    completionDate: "2026-01-20",
    featured: false,
    order: 7,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    screenshots: [],
    liveUrl: "https://www.zillow.com",
    githubUrl: "",
    caseStudy: "A real estate platform designed to make property discovery feel premium and effortless. Map-based search interface allows users to explore neighborhoods intuitively. AI recommendations learn from user behavior to suggest relevant properties.",
    metrics: "3× lead generation",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-20T00:00:00Z",
  },
  {
    id: generateId(),
    title: "Creative Agency",
    category: "Digital Agency",
    description: "Full-service agency website with case studies, team showcase, service offerings, and client testimonials.",
    longDescription: "A premium agency website that communicates capability and credibility. Features include an immersive hero section with portfolio highlights, detailed case studies with measurable results, a team showcase with individual profiles, and integrated client testimonial carousel.",
    technologies: ["Next.js", "Framer Motion", "MDX", "Vercel"],
    clientName: "",
    completionDate: "2026-01-05",
    featured: false,
    order: 8,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80",
    screenshots: [],
    liveUrl: "https://vercel.com",
    githubUrl: "",
    caseStudy: "A creative agency website built to showcase work while demonstrating technical expertise. Case studies follow a proven structure: challenge, approach, solution, and results. Each project page includes rich imagery and client testimonials.",
    metrics: "+40% conversion rate",
    createdAt: "2025-12-15T00:00:00Z",
    updatedAt: "2026-01-05T00:00:00Z",
  },
];

export function seedPortfolio() {
  savePortfolioProjects(DEMO_PROJECTS);
  console.log(`✅ Seeded ${DEMO_PROJECTS.length} portfolio projects`);
}
