// ============================================================
// Nova Webs — Seed Data
// Run this to initialize portfolio with sample projects.
// ============================================================

import { savePortfolioProjects, generateId, type PortfolioProject } from "./data-store";

const DEMO_PROJECTS: PortfolioProject[] = [
  {
    id: generateId(),
    title: "Restaurant Website",
    category: "Restaurant & Cafe",
    description: "A modern dining platform with immersive menu browsing, table reservation system, and real-time order management.",
    longDescription: "A complete digital ecosystem for a premium dining experience. Features include an interactive menu with dietary filters, a seamless table reservation engine with real-time availability, online ordering with payment integration, and a customer loyalty program.",
    technologies: ["Next.js", "Stripe", "Tailwind CSS", "Prisma"],
    clientName: "",
    completionDate: "2026-06-15",
    featured: true,
    order: 1,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    screenshots: [],
    liveUrl: "https://nextjs-restaurant.vercel.app",
    githubUrl: "",
    caseStudy: "This restaurant website was designed to create an immersive online dining experience that mirrors the quality of the physical restaurant. The menu system features high-resolution photography, detailed descriptions, and dietary filters. The reservation system integrates with the restaurant's table management to provide real-time availability.",
    metrics: "+120% online reservations",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-15T00:00:00Z",
  },
  {
    id: generateId(),
    title: "Gym & Fitness",
    category: "Health & Fitness",
    description: "High-performance fitness brand platform with class scheduling, membership management, and trainer profiles.",
    longDescription: "A dynamic fitness platform that drives membership growth. Key features include a class scheduling system with real-time capacity tracking, member profiles with progress tracking, trainer onboarding and profile management, and integrated payment processing for memberships.",
    technologies: ["React", "Node.js", "MongoDB", "Framer Motion"],
    clientName: "",
    completionDate: "2026-05-20",
    featured: true,
    order: 2,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80",
    screenshots: [],
    liveUrl: "https://gym-website-demo.vercel.app",
    githubUrl: "",
    caseStudy: "The gym website was built to convert visitors into members. The hero section features motivational imagery and a clear value proposition. Class schedules are displayed in an easy-to-navigate grid with filter options. The membership page clearly outlines tiers with visual comparison tables.",
    metrics: "+85% membership signups",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-20T00:00:00Z",
  },
  {
    id: generateId(),
    title: "Portfolio Website",
    category: "Creative Portfolio",
    description: "Minimalist designer portfolio with full-screen project galleries, custom cursor, and built-in CMS.",
    longDescription: "An award-winning portfolio website that puts the work front and center. Features include full-screen project galleries with smooth transitions, a custom cursor that responds to page elements, a built-in CMS for easy content updates, and subtle micro-interactions throughout.",
    technologies: ["Next.js", "GSAP", "Sanity CMS", "Tailwind CSS"],
    clientName: "",
    completionDate: "2026-04-10",
    featured: true,
    order: 3,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80",
    screenshots: [],
    liveUrl: "https://portfolio-demo-eight.vercel.app",
    githubUrl: "",
    caseStudy: "This portfolio website was designed to let the work speak for itself. The minimalist layout puts project imagery front and center, with subtle animations that guide visitors through the portfolio. The custom CMS integration allows the designer to update projects independently.",
    metrics: "Featured on Awwwards",
    createdAt: "2026-04-01T00:00:00Z",
    updatedAt: "2026-04-10T00:00:00Z",
  },
  {
    id: generateId(),
    title: "SaaS Platform",
    category: "Software & SaaS",
    description: "B2B analytics dashboard with real-time metrics, team collaboration, subscription billing, and API access.",
    longDescription: "A comprehensive SaaS platform for data-driven teams. Features include real-time analytics dashboards with customizable widgets, team collaboration tools with role-based access, subscription billing with tiered pricing, and a public API for integrations.",
    technologies: ["Next.js", "TypeScript", "PostgreSQL", "Chart.js"],
    clientName: "",
    completionDate: "2026-03-25",
    featured: true,
    order: 4,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    screenshots: [],
    liveUrl: "https://saas-dashboard-demo.vercel.app",
    githubUrl: "",
    caseStudy: "The SaaS platform was built from the ground up to handle enterprise-scale data processing. The frontend uses Next.js for optimal performance, while the backend leverages PostgreSQL for complex queries. The dashboard provides real-time insights with interactive charts.",
    metrics: "3× lead generation",
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-03-25T00:00:00Z",
  },
  {
    id: generateId(),
    title: "E-Commerce Store",
    category: "Online Retail",
    description: "Full-featured online marketplace with product catalog, secure checkout, inventory sync, and admin panel.",
    longDescription: "A complete e-commerce solution built for scale. Features include a dynamic product catalog with advanced search and filtering, secure checkout with multiple payment options, real-time inventory management with supplier sync, and a comprehensive admin dashboard for order management.",
    technologies: ["Next.js", "Stripe", "Sanity", "Redis"],
    clientName: "",
    completionDate: "2026-03-01",
    featured: true,
    order: 5,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
    screenshots: [],
    liveUrl: "https://ecommerce-demo-one.vercel.app",
    githubUrl: "",
    caseStudy: "This e-commerce platform was designed to maximize conversions while maintaining a premium brand experience. The product pages feature high-resolution imagery, detailed specifications, and customer reviews. The checkout flow has been optimized to reduce cart abandonment.",
    metrics: "+150% revenue",
    createdAt: "2026-02-15T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: generateId(),
    title: "Real Estate Portal",
    category: "Property & Realty",
    description: "Premium property marketplace with 3D virtual tours, AI recommendations, mortgage calculator, and agent profiles.",
    longDescription: "A cutting-edge real estate platform that transforms property discovery. Features include interactive property maps with neighborhood insights, 3D virtual tours for immersive previews, AI-powered property recommendations based on user preferences, and a mortgage calculator with real-time rates.",
    technologies: ["Next.js", "Three.js", "Mapbox", "FastAPI"],
    clientName: "",
    completionDate: "2026-02-10",
    featured: false,
    order: 6,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    screenshots: [],
    liveUrl: "https://realestate-demo-nine.vercel.app",
    githubUrl: "",
    caseStudy: "The real estate portal was designed to make property discovery feel premium and effortless. The map-based search interface allows users to explore neighborhoods intuitively. AI recommendations learn from user behavior to suggest relevant properties.",
    metrics: "3× lead generation",
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-02-10T00:00:00Z",
  },
  {
    id: generateId(),
    title: "Clinic Website",
    category: "Healthcare & Dental",
    description: "Modern healthcare platform with patient portal, online appointment booking, treatment galleries, and telemedicine.",
    longDescription: "A trust-building healthcare website that makes patients feel welcome. Features include an online appointment booking system with real-time slot availability, a patient portal for medical records and communication, treatment galleries with before/after imagery, and secure telemedicine integration.",
    technologies: ["React", "Twilio", "Tailwind CSS", "Supabase"],
    clientName: "",
    completionDate: "2026-01-15",
    featured: false,
    order: 7,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=800&q=80",
    screenshots: [],
    liveUrl: "https://clinic-website-demo.vercel.app",
    githubUrl: "",
    caseStudy: "The clinic website was designed to reduce patient anxiety and build trust from the first visit. The clean, professional design uses calming colors and warm imagery. The online booking system has reduced phone call volume by 40%.",
    metrics: "+60% new patients",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    id: generateId(),
    title: "Creative Agency",
    category: "Digital Agency",
    description: "Full-service agency website with case studies, team showcase, service offerings, and client testimonials.",
    longDescription: "A premium agency website that communicates capability and credibility. Features include an immersive hero section with portfolio highlights, detailed case studies with measurable results, a team showcase with individual profiles, and integrated client testimonial carousel.",
    technologies: ["Next.js", "Framer Motion", "MDX", "Vercel"],
    clientName: "",
    completionDate: "2026-01-05",
    featured: false,
    order: 8,
    status: "published",
    thumbnail: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80",
    screenshots: [],
    liveUrl: "https://agency-demo-six.vercel.app",
    githubUrl: "",
    caseStudy: "This agency website was built to showcase creative work while demonstrating technical expertise. The case studies follow a proven structure: challenge, approach, solution, and results. Each project page includes multiple imagery and a testimonial from the client.",
    metrics: "+40% conversion rate",
    createdAt: "2025-12-15T00:00:00Z",
    updatedAt: "2026-01-05T00:00:00Z",
  },
];

export function seedPortfolio() {
  savePortfolioProjects(DEMO_PROJECTS);
  console.log(`✅ Seeded ${DEMO_PROJECTS.length} portfolio projects`);
}
